# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "client" do |machine|
    machine.vm.hostname = "client"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "r1" do |machine|
    machine.vm.hostname = "r1"
    machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "r2" do |machine|
    machine.vm.hostname = "r2"
    machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
    machine.vm.network "private_network", virtualbox__intnet: "LAN4", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "s1" do |machine|
    machine.vm.hostname = "s1"
    machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  config.vm.define "s2" do |machine|
    machine.vm.hostname = "s2"
    machine.vm.network "private_network", virtualbox__intnet: "LAN4", auto_config: false
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end
end
