# Vagrantfile per l'esame "Amministrazione di Sistemi T"
# Nome: Davide Chirichella
# Matricola: 0001071414

# -*- mode: ruby -*-
# vi: set ft=ruby :

# numero di macchine virtuali
NUM_WORKSTATIONS = 1

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.define "Manager" do |machine|

    # hostname
    machine.vm.hostname = "Manager"

    # configurazione rete
    machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false

    # altre configurazioni
    machine.vm.synced_folder ".", "/vagrant", disabled: true
    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
    end
  end

  (1..NUM_WORKSTATIONS).each do |i|
    config.vm.define "WS#{i}" do |machine|

      # hostname
      machine.vm.hostname = "WS#{i}"
      
      # configurazione rete
      machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false

      # altre configurazioni
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end


end
