/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "RPC_xFile.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct OutputVisualizza *
visualizza_prenotazioni_1(InputVisualizza *argp, CLIENT *clnt)
{
	static struct OutputVisualizza clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, visualizza_prenotazioni,
		(xdrproc_t) xdr_InputVisualizza, (caddr_t) argp,
		(xdrproc_t) xdr_OutputVisualizza, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
elimina_monopattino_1(InputElimina *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, elimina_monopattino,
		(xdrproc_t) xdr_InputElimina, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
