/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME_SIZE 30
#define MAX_LIST_SIZE 6

struct Riga {
	char id[MAX_NAME_SIZE];
	char cartaId[6];
	char marca[7];
	char img[MAX_NAME_SIZE];
};
typedef struct Riga Riga;

struct InputElimina {
	char id[MAX_NAME_SIZE];
};
typedef struct InputElimina InputElimina;

struct InputVisualizza {
	char marca[7];
};
typedef struct InputVisualizza InputVisualizza;

struct OutputVisualizza {
	Riga prenotazioni[MAX_LIST_SIZE];
	int numPrenotazioni;
};
typedef struct OutputVisualizza OutputVisualizza;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define visualizza_prenotazioni 1
extern  struct OutputVisualizza * visualizza_prenotazioni_1(InputVisualizza *, CLIENT *);
extern  struct OutputVisualizza * visualizza_prenotazioni_1_svc(InputVisualizza *, struct svc_req *);
#define elimina_monopattino 2
extern  int * elimina_monopattino_1(InputElimina *, CLIENT *);
extern  int * elimina_monopattino_1_svc(InputElimina *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define visualizza_prenotazioni 1
extern  struct OutputVisualizza * visualizza_prenotazioni_1();
extern  struct OutputVisualizza * visualizza_prenotazioni_1_svc();
#define elimina_monopattino 2
extern  int * elimina_monopattino_1();
extern  int * elimina_monopattino_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Riga (XDR *, Riga*);
extern  bool_t xdr_InputElimina (XDR *, InputElimina*);
extern  bool_t xdr_InputVisualizza (XDR *, InputVisualizza*);
extern  bool_t xdr_OutputVisualizza (XDR *, OutputVisualizza*);

#else /* K&R C */
extern bool_t xdr_Riga ();
extern bool_t xdr_InputElimina ();
extern bool_t xdr_InputVisualizza ();
extern bool_t xdr_OutputVisualizza ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
