---
- name: Copy files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/vagrant/
    owner: vagrant
    group: vagrant
    
    # permessi notevoli:
    # 0600: il proprietario può leggere e scrivere, gli altri non possono fare nulla
    # 0644: il proprietario può leggere e scrivere, gli altri possono solo leggere
    # 0755: il proprietario può leggere, scrivere ed eseguire, gli altri possono leggere ed eseguire
    # 0777: tutti possono leggere, scrivere ed eseguire
    # 0750: il proprietario può leggere, scrivere ed eseguire, il gruppo può leggere ed eseguire, gli altri non possono fare nulla

    mode: "700"
  loop:
    - "script.sh"
    
- name: Copy Unitfile for the service 
  ansible.builtin.copy:
    src: '{{ service }}.service'
    dest: '/etc/systemd/system/{{ service }}.service'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Enable and start service