---
- name: Install snmpd
  ansible.builtin.apt:
    name: snmpd
    state: present

- name: Configure snmpd
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: Restart snmpd

- name: Enable privileged scripts
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: 'Debian-snmp ALL=(root) NOPASSWD: /usr/bin/ls -l /home/exam/.ssh/authorized_keys'
