/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_FileName (XDR *xdrs, FileName *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->filename, MAX_NAME_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DirName (XDR *xdrs, DirName *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->dirname, MAX_NAME_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputLista (XDR *xdrs, OutputLista *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->elementi, MAX_LIST_SIZE,
		sizeof (DirName), (xdrproc_t) xdr_DirName))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dimLista))
		 return FALSE;
	return TRUE;
}
