- name: Ensure the home directory for user {{ ssh_user }} exists
  ansible.builtin.file:
    path: /home/{{ ssh_user }}
    state: directory
    mode: '0755'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: Ensure the .ssh directory exists for user {{ ssh_user }}
  ansible.builtin.file:
    path: /home/{{ ssh_user }}/.ssh
    state: directory
    mode: '0700'
    owner: "{{ ssh_user }}"
    group: "{{ ssh_user }}"

- name: Copy the public key to the authorized_keys file for user {{ ssh_user }}
  ansible.builtin.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
