---
- hosts: all
  become: true
  roles:
#   - base_set_proxy
    - base_common

- hosts: R*
  become: true
  roles:

- hosts: C*
  become: true
  roles:
    - ldap_basic_server_user

- hosts: S*
  become: true
  roles:
