---
- hosts: all
  become: true
  roles:
#   - role: base_set_proxy
    - role: base_common

- hosts: R*
  become: true
  roles:

- hosts: C*
  become: true
  roles:

- hosts: S*
  become: true
  roles:
