# Vagrantfile per l'esame "Amministrazione di Sistemi T"
# Nome: Davide Chirichella
# Matricola: 00010714141

# -*- mode: ruby -*-
# vi: set ft=ruby :

# numero di macchine virtuali
NUM_CLIENTS = 1
NUM_ROUTERS = 1
NUM_SERVERS = 1

# indirizzi MAC delle macchine virtuali
MAC_ADRESSES = {
  "C1" => "000000000001",
  "R1" => "000000000002",
  "S1" => "000000000003",
}

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  (1..NUM_CLIENTS).each do |i|
    config.vm.define "C#{i}" do |machine|

      # hostname
      machine.vm.hostname = "C#{i}"

      # configurazione rete
      machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false, ip: "10.1.1.#{10 + i}", mac: MAC_ADRESSES["C#{i}"]
      # machine.vm.network "private_network", ip: "10.1.1.#{10 + i}", virtualbox__intnet: "NET1"
      # machine.vm.base_mac = MAC_ADRESSES["C#{i}"]

      # machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false, mac: MAC_ADRESSES["C#{i}"]

      # altre configurazioni
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end
  
  (1..NUM_ROUTERS).each do |i|
    config.vm.define "R#{i}" do |machine|
      # hostname
      machine.vm.hostname = "R#{i}"
      
      # configurazione rete
      machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false
      
      # altre configurazioni
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end
  
  # Configurazione singolo router

  #config.vm.define "R" do |machine|
  #  machine.vm.hostname = "R"
  #  machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false
  #  machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false
  #  machine.vm.synced_folder ".", "/vagrant", disabled: true
  #  machine.vm.provision "ansible" do |ansible|
  #    ansible.playbook = "site.yml"
  #  end
  #end

  (1..NUM_SERVERS).each do |i|
    config.vm.define "S#{i}" do |machine|

      # hostname
      machine.vm.hostname = "S#{i}"
      
      # configurazione rete
      machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false

      # altre configurazioni
      machine.vm.synced_folder ".", "/vagrant", disabled: true
      machine.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
      end
    end
  end


end
