/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Matricola (XDR *xdrs, Matricola *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->matricola, MAX_NAME_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputElimina (XDR *xdrs, InputElimina *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->matricola, MAX_NAME_SIZE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputVisualizza (XDR *xdrs, OutputVisualizza *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->risultato, MAX_LIST_SIZE,
		sizeof (Matricola), (xdrproc_t) xdr_Matricola))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dimLista))
		 return FALSE;
	return TRUE;
}
