/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME_SIZE 30
#define MAX_LIST_SIZE 5

struct Matricola {
	char matricola[MAX_NAME_SIZE];
};
typedef struct Matricola Matricola;

struct InputElimina {
	char matricola[MAX_NAME_SIZE];
};
typedef struct InputElimina InputElimina;

struct OutputVisualizza {
	Matricola risultato[MAX_LIST_SIZE];
	int dimLista;
};
typedef struct OutputVisualizza OutputVisualizza;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define elimina_prenotazione 1
extern  int * elimina_prenotazione_1(InputElimina *, CLIENT *);
extern  int * elimina_prenotazione_1_svc(InputElimina *, struct svc_req *);
#define visualizza_multiple 2
extern  struct OutputVisualizza * visualizza_multiple_1(void *, CLIENT *);
extern  struct OutputVisualizza * visualizza_multiple_1_svc(void *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define elimina_prenotazione 1
extern  int * elimina_prenotazione_1();
extern  int * elimina_prenotazione_1_svc();
#define visualizza_multiple 2
extern  struct OutputVisualizza * visualizza_multiple_1();
extern  struct OutputVisualizza * visualizza_multiple_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Matricola (XDR *, Matricola*);
extern  bool_t xdr_InputElimina (XDR *, InputElimina*);
extern  bool_t xdr_OutputVisualizza (XDR *, OutputVisualizza*);

#else /* K&R C */
extern bool_t xdr_Matricola ();
extern bool_t xdr_InputElimina ();
extern bool_t xdr_OutputVisualizza ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
