---
- hosts: all
  become: true
  roles:
#   - role: base_set_proxy
    - role: base_common

- hosts: Controller
  become: true
  roles:
    - net_ipforward
    - net_dnsmasq
    - net_controller
    - log_rsyslog_controller
    - scripts_controller
    - snmp_controller

- hosts: Agent1
  become: true
  roles:
    - net_agent
    - scripts_agent1
    - log_rsyslog_agent
    - snmp_agent

- hosts: Agent2
  become: true
  roles:
    - net_agent
    - scripts_agent2
    - snmp_agent
    - log_rsyslog_agent
