---
- name: Restart networking
  service:
    name: networking
    state: restarted

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Add user temp on LDAP
  ansible.builtin.shell:
    cmd: ldapadd -x -D "cn=admin,dc=labammsis" -w "gennaio.marzo" -H ldap:/// -f /root/temp.ldif

