/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "esame.h"

bool_t
xdr_Matricola (XDR *xdrs, Matricola *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->matricola, MAX_DIM_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputSoglia (XDR *xdrs, OutputSoglia *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->matricole, MAX_DIM_LIST,
		sizeof (Matricola), (xdrproc_t) xdr_Matricola))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numMatricole))
		 return FALSE;
	return TRUE;
}
