/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESAME_H_RPCGEN
#define _ESAME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_DIM_NAME 30
#define MAX_DIM_LIST 5

struct Matricola {
	char matricola[MAX_DIM_NAME];
};
typedef struct Matricola Matricola;

struct OutputSoglia {
	Matricola matricole[MAX_DIM_LIST];
	int numMatricole;
};
typedef struct OutputSoglia OutputSoglia;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ELIMINA_PRENOTAZIONE 1
extern  int * elimina_prenotazione_1(Matricola *, CLIENT *);
extern  int * elimina_prenotazione_1_svc(Matricola *, struct svc_req *);
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA 2
extern  struct OutputSoglia * visualizza_voto_maggiore_soglia_1(int *, CLIENT *);
extern  struct OutputSoglia * visualizza_voto_maggiore_soglia_1_svc(int *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ELIMINA_PRENOTAZIONE 1
extern  int * elimina_prenotazione_1();
extern  int * elimina_prenotazione_1_svc();
#define VISUALIZZA_VOTO_MAGGIORE_SOGLIA 2
extern  struct OutputSoglia * visualizza_voto_maggiore_soglia_1();
extern  struct OutputSoglia * visualizza_voto_maggiore_soglia_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Matricola (XDR *, Matricola*);
extern  bool_t xdr_OutputSoglia (XDR *, OutputSoglia*);

#else /* K&R C */
extern bool_t xdr_Matricola ();
extern bool_t xdr_OutputSoglia ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ESAME_H_RPCGEN */
