/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "esame.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
elimina_prenotazione_1(Matricola *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ELIMINA_PRENOTAZIONE,
		(xdrproc_t) xdr_Matricola, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct OutputSoglia *
visualizza_voto_maggiore_soglia_1(int *argp, CLIENT *clnt)
{
	static struct OutputSoglia clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, VISUALIZZA_VOTO_MAGGIORE_SOGLIA,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_OutputSoglia, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
