- hosts: all                 # Applica il playbook a tutti gli host specificati nell'inventory
  become: true              # Esegue i comandi con privilegi di root (sudo)

  tasks:
    # ✅ Copia il file di configurazione per l'interfaccia eth1
    - name: Configura eth1 con indirizzo statico (dopo validazione)
      ansible.builtin.copy:
        src: r1eth1                                # File di configurazione locale (nel progetto Ansible)
        dest: /etc/network/interfaces.d/eth1       # Dove viene copiato sul target
        validate: /usr/sbin/ifup --no-act -i %s eth1  # Valida il file prima della copia
      notify: Restart Networking                    # Richiama un handler se il file è cambiato

    # ✅ Copia il file di configurazione per l'interfaccia eth2
    - name: Configura eth2 con indirizzo statico (dopo validazione)
      ansible.builtin.copy:
        src: r1eth2
        dest: /etc/network/interfaces.d/eth2
        validate: /usr/sbin/ifup --no-act -i %s eth2
      notify: Restart Networking

    # 🔁 Sostituisce "allow-hotplug" con "auto" nel file principale delle interfacce
    - name: Rendi l'interfaccia eth0 automatica (non solo plug and play)
      ansible.builtin.replace:
        path: '/etc/network/interfaces'
        regexp: '^allow\-hotplug'                   # Cerca le righe che iniziano con "allow-hotplug"
        replace: 'auto'                             # Le sostituisce con "auto"
        validate: /usr/sbin/ifup --no-act -i %s eth0

    # 🔁 Assicura che l'inoltro IP sia abilitato (routing tra interfacce)
    - name: Abilita il forwarding IPv4
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        line: 'net.ipv4.ip_forward=1'              # Aggiunge o aggiorna la linea per il forwarding
      notify: Reload sysctl                         # Ricarica la configurazione sysctl

  handlers:
    # 🔄 Riavvia il servizio di rete se una configurazione cambia
    - name: Restart Networking
      ansible.builtin.service:
        name: networking
        state: restarted

    # 🔄 Ricarica la configurazione sysctl (senza reboot)
    - name: Reload sysctl
      ansible.builtin.command: /usr/sbin/sysctl -p
