---
- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Start and enable dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: started
    enabled: true
