/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESAME_H_RPCGEN
#define _ESAME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME_SIZE 256
#define MAX_LIST_SIZE 6

struct NomeFile {
	char nome[MAX_NAME_SIZE];
};
typedef struct NomeFile NomeFile;

struct InputConta {
	char fileName[MAX_NAME_SIZE];
	char linea[MAX_NAME_SIZE];
};
typedef struct InputConta InputConta;

struct OutputLista {
	NomeFile files[MAX_LIST_SIZE];
	int numFiles;
	int status;
};
typedef struct OutputLista OutputLista;

struct InputLista {
	char dirName[MAX_LIST_SIZE];
	char prefisso[MAX_NAME_SIZE];
};
typedef struct InputLista InputLista;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define conta_occorrenze_linea 1
extern  int * conta_occorrenze_linea_1(InputConta *, CLIENT *);
extern  int * conta_occorrenze_linea_1_svc(InputConta *, struct svc_req *);
#define lista_file_prefisso 2
extern  struct OutputLista * lista_file_prefisso_1(InputLista *, CLIENT *);
extern  struct OutputLista * lista_file_prefisso_1_svc(InputLista *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define conta_occorrenze_linea 1
extern  int * conta_occorrenze_linea_1();
extern  int * conta_occorrenze_linea_1_svc();
#define lista_file_prefisso 2
extern  struct OutputLista * lista_file_prefisso_1();
extern  struct OutputLista * lista_file_prefisso_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_NomeFile (XDR *, NomeFile*);
extern  bool_t xdr_InputConta (XDR *, InputConta*);
extern  bool_t xdr_OutputLista (XDR *, OutputLista*);
extern  bool_t xdr_InputLista (XDR *, InputLista*);

#else /* K&R C */
extern bool_t xdr_NomeFile ();
extern bool_t xdr_InputConta ();
extern bool_t xdr_OutputLista ();
extern bool_t xdr_InputLista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ESAME_H_RPCGEN */
