---
- name: Copy a new eth1 configuration "interfaces" file into place, after passing validation with ifup
  ansible.builtin.copy:
    src: r1eth1
    dest: /etc/network/interfaces.d/r1eth1
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/ifup --no-act -i %s eth1
  notify: Restart Networking