password: gennaio.marzo

users:
  - dn: uid=dave,ou=People,dc=labammsis
    givenName: Davide
    cn: Davide
    sn: Berardi
    mail: davide.berardi@unibo.it
    uid: dave
    uidNumber: 10000
    gidNumber: 10000
    homeDirectory: /home/dave
    loginShell: /bin/bash
    gecos: "Davide \"Dave\" Berardi"
    userPassword: "{crypt}x"

  - uid: alice
    givenName: Alice
    cn: Alice
    sn: Rossi
    mail: alice.rossi@unibo.it
    uidNumber: 10001
    gidNumber: 10000
    homeDirectory: /home/alice
    loginShell: /bin/bash
    gecos: Alice Rossi
    userPassword: "{crypt}y"

  - uid: bob
    givenName: Bob
    cn: Bob
    sn: Bianchi
    # ← no “mail:” here
    uidNumber: 10002
    gidNumber: 10000
    homeDirectory: /home/bob
    loginShell: /bin/bash
    gecos: Bob Bianchi
    userPassword: "{crypt}z"

userspassword:
  - uid: dave
    passwd: pippo
  - uid: alice
    passwd: test
  - uid: bob
    passwd: test

usergroups:
  - cn: dave
    gidNumber: 10000
