---
- name: Ensure ~/.ssh directory exists
  file:
    path: /home/vagrant/.ssh
    state: directory
    mode: '0700'
    owner: vagrant
    group: vagrant

- name: Generate SSH key on guest if not exists
  become: true
  become_user: vagrant
  command: ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -N ''
  args:
    creates: /home/vagrant/.ssh/id_rsa

- name: Copy public key from guest to host
  fetch:
    src: /home/vagrant/.ssh/id_rsa.pub
    dest: ./id_rsa.pub
    flat: yes