---
- name: Install snmpd
  ansible.builtin.apt:
    name: snmpd
    state: present

# Eventuale installazione pacchetti
- name: Install tcpdump
  ansible.builtin.apt:
    name: tcpdump
    state: present

- name: Configure snmpd
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: Restart snmpd

#  Enable tcpdump and rm via sudo for Debian-snmp user 
- name: Enable privileged tcpdump
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    # abilita comandi specifici (tcpdump e rm)
    # i comandi vengono eseguiti come root
    line: 'Debian-snmp ALL=(root) NOPASSWD: /usr/bin/tcpdump, /usr/bin/rm'

# Enable execution of two custom scripts via sudo
- name: Enable privileged scripts
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    # abilita l'esecuzione di script personalizzati.
    # gli script possono essere eseguiti con privilegi di qualsiasi utente (ALL)
    line: 'Debian-snmp ALL=(ALL) NOPASSWD: /home/vagrant/create-dump.sh, /home/vagrant/delete-dump.sh'
