---
- name: Ensure .ssh directory exists for "{{ user }}"
  file:
    path: /home/"{{ user }}"/.ssh
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'

- name: Generate SSH key pair for "{{ user }}" (if not already present)
  become: true
  become_user: "{{ user }}"
  openssh_keypair:
    path: /home/"{{ user }}"/.ssh/id_rsa
    type: rsa
    size: 2048
    mode: '0600'
    force: false
