/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "files.h"

bool_t
xdr_FileName (XDR *xdrs, FileName *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, MAX_FILE_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputElimina (XDR *xdrs, InputElimina *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, MAX_FILE_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputLista (XDR *xdrs, InputLista *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->dirName, MAX_FILE_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->carattere))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numOccorrenze))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputLista (XDR *xdrs, OutputLista *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomiFile, MAX_FILE_LIST,
		sizeof (FileName), (xdrproc_t) xdr_FileName))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numFile))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputElimina (XDR *xdrs, OutputElimina *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numEliminati))
		 return FALSE;
	return TRUE;
}
