/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILES_H_RPCGEN
#define _FILES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_FILE_NAME 30
#define MAX_FILE_LIST 7

struct FileName {
	char name[MAX_FILE_NAME];
};
typedef struct FileName FileName;

struct InputElimina {
	char fileName[MAX_FILE_NAME];
};
typedef struct InputElimina InputElimina;

struct InputLista {
	char dirName[MAX_FILE_NAME];
	char carattere;
	int numOccorrenze;
};
typedef struct InputLista InputLista;

struct OutputLista {
	FileName nomiFile[MAX_FILE_LIST];
	int numFile;
	int status;
};
typedef struct OutputLista OutputLista;

struct OutputElimina {
	int numEliminati;
};
typedef struct OutputElimina OutputElimina;

#define ESAME_PROG 0x20000014
#define ESAME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LISTA_FILE_CARATTERE 1
extern  struct OutputLista * lista_file_carattere_1(InputLista *, CLIENT *);
extern  struct OutputLista * lista_file_carattere_1_svc(InputLista *, struct svc_req *);
#define ELIMINA_OCCORRENZE 2
extern  struct OutputElimina * elimina_occorrenze_1(InputElimina *, CLIENT *);
extern  struct OutputElimina * elimina_occorrenze_1_svc(InputElimina *, struct svc_req *);
extern int esame_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LISTA_FILE_CARATTERE 1
extern  struct OutputLista * lista_file_carattere_1();
extern  struct OutputLista * lista_file_carattere_1_svc();
#define ELIMINA_OCCORRENZE 2
extern  struct OutputElimina * elimina_occorrenze_1();
extern  struct OutputElimina * elimina_occorrenze_1_svc();
extern int esame_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileName (XDR *, FileName*);
extern  bool_t xdr_InputElimina (XDR *, InputElimina*);
extern  bool_t xdr_InputLista (XDR *, InputLista*);
extern  bool_t xdr_OutputLista (XDR *, OutputLista*);
extern  bool_t xdr_OutputElimina (XDR *, OutputElimina*);

#else /* K&R C */
extern bool_t xdr_FileName ();
extern bool_t xdr_InputElimina ();
extern bool_t xdr_InputLista ();
extern bool_t xdr_OutputLista ();
extern bool_t xdr_OutputElimina ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILES_H_RPCGEN */
