/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "files.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct OutputLista *
lista_file_carattere_1(InputLista *argp, CLIENT *clnt)
{
	static struct OutputLista clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LISTA_FILE_CARATTERE,
		(xdrproc_t) xdr_InputLista, (caddr_t) argp,
		(xdrproc_t) xdr_OutputLista, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct OutputElimina *
elimina_occorrenze_1(InputElimina *argp, CLIENT *clnt)
{
	static struct OutputElimina clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ELIMINA_OCCORRENZE,
		(xdrproc_t) xdr_InputElimina, (caddr_t) argp,
		(xdrproc_t) xdr_OutputElimina, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
